### ISSUE TITLE
Modified AudioLink component settings don't manifest in-world

### ISSUE THREAD

**Issue by teehzero** [llealloo/audiolink#299]
Today, if you make changes to the AudioLink component and upload to a VRC world, only the Gain control actually survives upload.
World used to test: https://vrchat.com/home/world/wrld_06ec7076-f5a6-4248-a786-0f222f524f61
AudioLink Component Settings: https://i.imgur.com/gaEndmq.png
In-game result: https://i.imgur.com/ZKBgv6S.png

The recent GlobalSlider bug gave me the idea to cut out the middle man and just move the slider for these controls directly in the editor, as opposed to on the AudioLink component, or via any other scripts and/or shaders. This works, but is far from user-friendly, and is not how this is supposed to work, as it was explained to me. My suspicion is that GlobalSlider is incorrectly re-initializing these values, but that might just be recency bias.

Working after directly modifying sliders in editor: https://i.imgur.com/yo6b9ES.png

**Comment by pema99** [comment]
Fixed in next release
