### ISSUE TITLE
Suggestion: Reduce Texture Size For Controller Icons

### ISSUE THREAD

**Issue by JLChnToZ** [llealloo/audiolink#306]
**Feature Description:**
As I observed, every time I upload a world contains a AudioLink controller, it includes controller icon textures but in unreasonably high resolution (1024x1024 each). I don't think it worth to be that large, so I suggests it can be convert to SDF/MSDF format with a much lower resolution to reduce build size. P.S. if I have those source (vector) files, I can help convert them.

**Additional context:**
![image](https://github.com/llealloo/audiolink/assets/4715281/88c7099d-57d0-4e99-8dc1-073bcc21ab3e)
![image](https://github.com/llealloo/audiolink/assets/4715281/a5df0bed-adf5-4f40-9a9d-6310fb6fca3e)
![image](https://github.com/llealloo/audiolink/assets/4715281/2edf78af-f01f-4a44-8854-a01b523afca7)
![image](https://github.com/llealloo/audiolink/assets/4715281/3b1fa155-5638-4244-a722-8efb3586b80c)

There are several more textures/icons I think they are too large as well, but I think it is enough to show above as examples.

**Comment by float3** [comment]
good point, we should do this

**Comment by float3** [comment]
I think clamping import size for now is a good start and then we should look into need, do we want to build msdf baking infrastructure inside of unity for futureproofing?

**Comment by JLChnToZ** [comment]
As I know MSDF baking requires external executable, IDK is it good to include the whole pipeline within AudioLink package.

**Comment by pema99** [comment]
If you are going to bake SDF textures for the icons I would just do it once, don't have to bother making baking infrastructure. I'm not personally familiar with tools for doing this, but if either of you would like to give it a shot I can provide guidance on how the controller shader is written (though I imagine the shader changes should be fairly straight forward?).

@llealloo might still have the source files lying around

**Comment by JLChnToZ** [comment]
I do have experience on doing this, I did it for all icons in my own video player.

Once I got the source files I could immediately work on this. 😉

**Comment by float3** [comment]
> As I know MSDF baking requires external executable, IDK is it good to include the whole pipeline within AudioLink package.

not in the package but in Audiolinkdev unity project in the repo, which isn't shipped to users
