### ISSUE TITLE
Change the default Ytdlp URL to something more tolerable

### ISSUE THREAD

**Issue by BluWizard10** [llealloo/audiolink#310]
Honestly?

The default song is hard to listen to, it's just a weird autotuned song that isn't even something one could dance to.

I really think it's time for a change, by using a song that not only hits on all Audio Bands, but is something that is easy to listen and dance to.

The AudioLink V2 World has one that would make a suitable candidate in my opinion. It's non-copyrighted and hits on all Audio Bands. It's something that I think anyone can listen to, more so than the current default song in Ytdlp Player.

Either way, let's start a discussion on this. I'm eager to see better candidates as a new default soundtrack for the Ytdlp Player.

**Comment by pema99** [comment]
We've changed to default song to [Shibuya](https://www.youtube.com/watch?v=vGXyAKy-X6s) by Rollthered, which they have licensed to use under creative commons.
