### ISSUE TITLE
AudiolinkAvatar prefab default volume too loud

### ISSUE THREAD

**Issue by Casuallynoted** [llealloo/audiolink#314]
**Describe the bug in detail:**
By default, the ytdlp player included in the AudioLinkAvatar prefab is set to a volume of .4, which is quite loud. Usually, it has to be set to something like .1 or .2 to be a reasonable volume on the average pc setup.

**Provide steps/code to reproduce the bug:**
-Put on headphones
-Drag and drop the prefab into the scene
-Hit play
-Suffer

**Expected behavior:**
Ideally, the volume should be set lower. Worst case, if it's too low, someone can adjust it- but having it be as loud as it is by default isn't great

**Comment by pema99** [comment]
Fair point. I'll change it to 0.2

**Comment by pema99** [comment]
bab2b8a0c1c3b520a412ce5ef0f74282c44f0547
