### ISSUE TITLE
Malformed `package.json` files

### ISSUE THREAD

**Issue by foxscore** [llealloo/audiolink#316]
**Describe the bug in detail:**
The `package.json` files in the release zips are missing the required fields `author.name` and `author.email`.
These fields are required as per the [specification](https://vcc.docs.vrchat.com/vpm/packages/#vpm-manifest-additions) and exclusion of these fields may lead to issues with software that expects it. *Especially since this is a "curated" package.*

**Provide steps/code to reproduce the bug:**
*N/A*

**Expected behavior:**
The `author.name` and `author.email` fields should be present in all past and future versions.

**Additional Information:**
*N/A*

**Comment by float3** [comment]
thanks for the report, will address this, out of curiosity is there anything that breaks because this is missing?

**Comment by float3** [comment]
note that in upm, at least:
>      Author of the package.
> 
> This object contains one required field (name) and** two optional fields (email) and (url).**
> 
> For example:
> { "name" : "John Doe",
>    "email" : "john.doe@example.com",
>    "url" : "http://john.doe.example.com/"
> }

email may not be required in vpm either

but we should add an email regardless, only need to figure out which maintainers email

**Comment by pema99** [comment]
Author isn't required by UPM at all. This is purely a VPM requirement. I don't think they rely on it anywhere, but the docs do state this, so it's a fair ask

**Comment by pema99** [comment]
If @llealloo is ok with it, we will use her info. Otherwise, mine
